INSERT INTO public."Torneos"
  (name, description, start_date, img_path, categories, end_date, inscription_end_date, manually_closed)
VALUES 
  ('Primavera 2023', 'El fin de semana del 12 al 14 de mayo, categorías masculinas y femeninas únicas. 15€ por inscripción.', '2023-05-12', NULL, ARRAY['MASC', 'FEM'], '2023-05-14', '2023-05-12', false),
  ('Primavera 2024', 'El fin de semana del 10 al 12 de mayo, categorías masculinas y femeninas únicas. 15€ por inscripción.', '2024-05-10', '10-05-2024.jpeg', ARRAY['MASC', 'FEM'], '2024-05-12', '2024-05-08', false),
  ('Mixto de Invierno 2024', 'El fin de semana del 20 al 22 de diciembre, 15€ por inscripción.', '2024-12-20', '20-12-2024.jpeg', NULL, '2024-12-22', '2024-12-16', false),
  ('Primavera 2025', 'El fin de semana del 9 al 11 de mayo, categorías masculinas y femeninas únicas. 20€ por inscripción y 15€ si eres socio.', '2025-05-09', '09-05-2025.jpeg', ARRAY['MASC', 'FEM'], '2025-05-11', '2025-05-04', false),
  ('Mixto de Otoño 2025', 'El fin de semana del 17 al 19 de octubre, 20€ por inscripción y 15€ si eres socio.', '2025-10-17', '17-10-2025.jpeg', NULL, '2025-10-19', '2025-10-13', false);

INSERT INTO public."Socios"
  (full_name)
VALUES
  ('Mónica Rodríguez Gavín'),
  ('Bonia Martínez Irimia'),
  ('Javier Hernández Martínez'),
  ('Ana Hernández Martínez'),
  ('Francisco Hernández Solís'),
  ('Paz López Teijo'),
  ('Santiago Rodríguez Gavín'),
  ('Teresa Castro Vega'),
  ('Marisa González Irimia'),
  ('Jose M. Muñoz Muñoz'),
  ('José Luis Iglesias Gallo'),
  ('Juan José López Díaz'),
  ('Laura Alonso Carracedo'),
  ('Carla Flórez Quintana'),
  ('Luis Lorido Carballeira'),
  ('Emilio Folgueiras Coto'),
  ('Iván Trabadelo Iglesias'),
  ('Ramón González Barcia'),
  ('Félix Villada Moirón'),
  ('José Luis Álvarez Bouso'),
  ('Xosé Castro Vega'),
  ('Antonio Martínez Irimia'),
  ('Hector Bello Godoy'),
  ('Javier Trashorras'),
  ('Andrés Seoane'),
  ('José Jorge Fiallega González'),
  ('Ángel Villada Moirón'),
  ('Isacc Canterla Rubio'),
  ('José L. Comendeiro López'),
  ('Jesús Coto Folgueiras'),
  ('Germán Linares Castro'),
  ('Pablo Pumar Alonso'),
  ('Mª José Pardo Rodríguez'),
  ('Paula Pérez Iglesias'),
  ('Moisés Fernández Marcos'),
  ('Manuel Liz López'),
  ('Mónica García Mon'),
  ('Mateo Melón Codillero'),
  ('Alfonso José Morcillo Panadero'),
  ('José Ramón Rodríguez García'),
  ('Susana Darriba Andión'),
  ('Adrián Cadenas González'),
  ('Miguel Rivas Castro'),
  ('Pablo López Rodríguez'),
  ('Beltrán García Darriba'),
  ('Andrea García Darriba');
