export { Instagram } from "./instagram";
export { Gmail } from "./gmail";
export { WhatsApp } from "./whatsapp";
export { Person } from "./person";
export { Trophy } from "./trophy";
export { Medal } from "./medal";
export { Dumbell } from "./dumbell";
export { Logo } from "./logo";
export { Telegram } from "./telegram";
