create type "public"."month_status" as enum ('draft', 'locked', 'confirmed');


  create table "public"."bonuses" (
    "id" bigint generated by default as identity not null,
    "player_id" bigint not null,
    "quantity" numeric not null default '0'::numeric,
    "month_id" bigint
      );


alter table "public"."bonuses" enable row level security;


  create table "public"."categories" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "order" numeric not null,
    "points_per_set" numeric not null default '3'::numeric
      );


alter table "public"."categories" enable row level security;


  create table "public"."inscriptions" (
    "id" bigint generated by default as identity not null,
    "tournament_id" bigint not null,
    "user_id" uuid not null,
    "phone_number" text not null,
    "category" text,
    "player1_full_name" text not null,
    "player2_full_name" text not null
      );


alter table "public"."inscriptions" enable row level security;


  create table "public"."match_participants" (
    "id" bigint generated by default as identity not null,
    "match_id" bigint not null,
    "player_id" bigint not null,
    "substitute_id" bigint
      );


alter table "public"."match_participants" enable row level security;


  create table "public"."matchdays" (
    "id" bigint generated by default as identity not null,
    "month_id" bigint not null,
    "order" numeric not null
      );


alter table "public"."matchdays" enable row level security;


  create table "public"."matches" (
    "id" bigint generated by default as identity not null,
    "matchday_id" bigint not null,
    "category_id" bigint not null
      );


alter table "public"."matches" enable row level security;


  create table "public"."members" (
    "id" bigint generated by default as identity not null,
    "full_name" text not null,
    "nickname" text,
    "is_active" boolean not null default true
      );


alter table "public"."members" enable row level security;


  create table "public"."months" (
    "id" bigint generated by default as identity not null,
    "season_id" bigint not null,
    "month" numeric not null,
    "status" public.month_status not null default 'draft'::public.month_status,
    "year" numeric not null,
    "has_fifth_category" boolean not null default true
      );


alter table "public"."months" enable row level security;


  create table "public"."player_category_assignments" (
    "id" bigint generated by default as identity not null,
    "player_id" bigint not null,
    "month_id" bigint not null,
    "category_id" bigint not null
      );


alter table "public"."player_category_assignments" enable row level security;


  create table "public"."seasons" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "start_date" date
      );


alter table "public"."seasons" enable row level security;


  create table "public"."sets" (
    "id" bigint generated by default as identity not null,
    "match_id" bigint not null,
    "order" numeric not null,
    "pair1_player1_id" bigint not null,
    "pair1_player2_id" bigint not null,
    "pair2_player1_id" bigint not null,
    "pair2_player2_id" bigint not null,
    "pair1_score" numeric not null,
    "pair2_score" numeric not null
      );


alter table "public"."sets" enable row level security;


  create table "public"."tournaments" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "description" text,
    "start_date" date not null,
    "img_path" text,
    "categories" text[],
    "end_date" date not null,
    "inscription_end_date" timestamp with time zone not null,
    "manually_closed" boolean not null
      );


alter table "public"."tournaments" enable row level security;

CREATE UNIQUE INDEX "Bonus_pkey" ON public.bonuses USING btree (id);

CREATE UNIQUE INDEX "Categorias_pkey" ON public.categories USING btree (id);

CREATE UNIQUE INDEX "Jornadas_pkey" ON public.matchdays USING btree (id);

CREATE UNIQUE INDEX "Jugador_Categoria_Mes_pkey" ON public.player_category_assignments USING btree (id);

CREATE UNIQUE INDEX "Meses_pkey" ON public.months USING btree (id);

CREATE UNIQUE INDEX "Partidos_pkey" ON public.matches USING btree (id);

CREATE UNIQUE INDEX "Sets_pkey" ON public.sets USING btree (id);

CREATE UNIQUE INDEX "Socios_pkey" ON public.members USING btree (id);

CREATE UNIQUE INDEX "Temporadas_pkey" ON public.seasons USING btree (id);

CREATE UNIQUE INDEX "Torneos_pkey" ON public.tournaments USING btree (id);

CREATE UNIQUE INDEX inscripciones_pkey ON public.inscriptions USING btree (id);

CREATE UNIQUE INDEX inscripciones_torneo_user_unique ON public.inscriptions USING btree (tournament_id, user_id);

CREATE UNIQUE INDEX jornadas_mes_number_unique ON public.matchdays USING btree (month_id, "order");

CREATE UNIQUE INDEX jugador_categoria_mes_unique ON public.player_category_assignments USING btree (month_id, player_id);

CREATE UNIQUE INDEX meses_month_year_temporada_unique ON public.months USING btree (month, year, season_id);

CREATE UNIQUE INDEX participacion_pkey ON public.match_participants USING btree (id);

CREATE UNIQUE INDEX unique_category_per_month ON public.player_category_assignments USING btree (month_id, player_id);

CREATE UNIQUE INDEX unique_month ON public.months USING btree (season_id, month);

alter table "public"."bonuses" add constraint "Bonus_pkey" PRIMARY KEY using index "Bonus_pkey";

alter table "public"."categories" add constraint "Categorias_pkey" PRIMARY KEY using index "Categorias_pkey";

alter table "public"."inscriptions" add constraint "inscripciones_pkey" PRIMARY KEY using index "inscripciones_pkey";

alter table "public"."match_participants" add constraint "participacion_pkey" PRIMARY KEY using index "participacion_pkey";

alter table "public"."matchdays" add constraint "Jornadas_pkey" PRIMARY KEY using index "Jornadas_pkey";

alter table "public"."matches" add constraint "Partidos_pkey" PRIMARY KEY using index "Partidos_pkey";

alter table "public"."members" add constraint "Socios_pkey" PRIMARY KEY using index "Socios_pkey";

alter table "public"."months" add constraint "Meses_pkey" PRIMARY KEY using index "Meses_pkey";

alter table "public"."player_category_assignments" add constraint "Jugador_Categoria_Mes_pkey" PRIMARY KEY using index "Jugador_Categoria_Mes_pkey";

alter table "public"."seasons" add constraint "Temporadas_pkey" PRIMARY KEY using index "Temporadas_pkey";

alter table "public"."sets" add constraint "Sets_pkey" PRIMARY KEY using index "Sets_pkey";

alter table "public"."tournaments" add constraint "Torneos_pkey" PRIMARY KEY using index "Torneos_pkey";

alter table "public"."bonuses" add constraint "bonuses_month_id_fkey" FOREIGN KEY (month_id) REFERENCES public.months(id) not valid;

alter table "public"."bonuses" validate constraint "bonuses_month_id_fkey";

alter table "public"."bonuses" add constraint "bonuses_player_id_fkey" FOREIGN KEY (player_id) REFERENCES public.members(id) not valid;

alter table "public"."bonuses" validate constraint "bonuses_player_id_fkey";

alter table "public"."inscriptions" add constraint "inscripciones_torneo_user_unique" UNIQUE using index "inscripciones_torneo_user_unique";

alter table "public"."inscriptions" add constraint "inscriptions_tournament_id_fkey" FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) ON DELETE CASCADE not valid;

alter table "public"."inscriptions" validate constraint "inscriptions_tournament_id_fkey";

alter table "public"."inscriptions" add constraint "inscriptions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."inscriptions" validate constraint "inscriptions_user_id_fkey";

alter table "public"."match_participants" add constraint "match_participants_match_id_fkey" FOREIGN KEY (match_id) REFERENCES public.matches(id) not valid;

alter table "public"."match_participants" validate constraint "match_participants_match_id_fkey";

alter table "public"."match_participants" add constraint "match_participants_player_id_fkey" FOREIGN KEY (player_id) REFERENCES public.members(id) not valid;

alter table "public"."match_participants" validate constraint "match_participants_player_id_fkey";

alter table "public"."match_participants" add constraint "match_participants_substitute_id_fkey" FOREIGN KEY (substitute_id) REFERENCES public.members(id) not valid;

alter table "public"."match_participants" validate constraint "match_participants_substitute_id_fkey";

alter table "public"."matchdays" add constraint "jornadas_mes_number_unique" UNIQUE using index "jornadas_mes_number_unique";

alter table "public"."matches" add constraint "matches_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.categories(id) not valid;

alter table "public"."matches" validate constraint "matches_category_id_fkey";

alter table "public"."matches" add constraint "matches_matchday_id_fkey" FOREIGN KEY (matchday_id) REFERENCES public.matchdays(id) not valid;

alter table "public"."matches" validate constraint "matches_matchday_id_fkey";

alter table "public"."months" add constraint "meses_month_year_temporada_unique" UNIQUE using index "meses_month_year_temporada_unique";

alter table "public"."months" add constraint "months_season_id_fkey" FOREIGN KEY (season_id) REFERENCES public.seasons(id) ON DELETE CASCADE not valid;

alter table "public"."months" validate constraint "months_season_id_fkey";

alter table "public"."months" add constraint "unique_month" UNIQUE using index "unique_month";

alter table "public"."player_category_assignments" add constraint "jugador_categoria_mes_unique" UNIQUE using index "jugador_categoria_mes_unique";

alter table "public"."player_category_assignments" add constraint "player_category_assignments_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.categories(id) not valid;

alter table "public"."player_category_assignments" validate constraint "player_category_assignments_category_id_fkey";

alter table "public"."player_category_assignments" add constraint "player_category_assignments_month_id_fkey" FOREIGN KEY (month_id) REFERENCES public.months(id) not valid;

alter table "public"."player_category_assignments" validate constraint "player_category_assignments_month_id_fkey";

alter table "public"."player_category_assignments" add constraint "player_category_assignments_player_id_fkey" FOREIGN KEY (player_id) REFERENCES public.members(id) not valid;

alter table "public"."player_category_assignments" validate constraint "player_category_assignments_player_id_fkey";

alter table "public"."player_category_assignments" add constraint "unique_category_per_month" UNIQUE using index "unique_category_per_month";

alter table "public"."sets" add constraint "sets_match_id_fkey" FOREIGN KEY (match_id) REFERENCES public.matches(id) not valid;

alter table "public"."sets" validate constraint "sets_match_id_fkey";

alter table "public"."sets" add constraint "sets_pair1_player1_id_fkey" FOREIGN KEY (pair1_player1_id) REFERENCES public.members(id) not valid;

alter table "public"."sets" validate constraint "sets_pair1_player1_id_fkey";

alter table "public"."sets" add constraint "sets_pair1_player2_id_fkey" FOREIGN KEY (pair1_player2_id) REFERENCES public.members(id) not valid;

alter table "public"."sets" validate constraint "sets_pair1_player2_id_fkey";

alter table "public"."sets" add constraint "sets_pair2_player1_id_fkey" FOREIGN KEY (pair2_player1_id) REFERENCES public.members(id) not valid;

alter table "public"."sets" validate constraint "sets_pair2_player1_id_fkey";

alter table "public"."sets" add constraint "sets_pair2_player2_id_fkey" FOREIGN KEY (pair2_player2_id) REFERENCES public.members(id) not valid;

alter table "public"."sets" validate constraint "sets_pair2_player2_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.create_season_with_months(p_name text, p_start_date date, p_months jsonb)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_id INT;
BEGIN
  INSERT INTO seasons (name, start_date)
  VALUES (p_name, p_start_date)
  RETURNING id INTO v_id;

  INSERT INTO months (season_id, month, year)
  SELECT v_id, (m->>'month')::int, (m->>'year')::int
  FROM jsonb_array_elements(p_months) AS m;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.generate_month_matches(p_month_id bigint, p_matches jsonb)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  m jsonb;

  matchday1_id bigint;
  matchday2_id bigint;

  match_id bigint;
BEGIN
  WITH matchdays_upsert AS (
    INSERT INTO matchdays (month_id, "order")
    VALUES (p_month_id, 1), (p_month_id, 2)
    ON CONFLICT (month_id, "order")
    DO UPDATE SET month_id = EXCLUDED.month_id
    RETURNING id, "order"
  )
  SELECT
    MAX(id) FILTER (WHERE "order" = 1),
    MAX(id) FILTER (WHERE "order" = 2)
  INTO matchday1_id, matchday2_id
  FROM matchdays_upsert;

  IF matchday1_id IS NULL OR matchday2_id IS NULL THEN
    RAISE EXCEPTION 'No se pudieron crear las jornadas';
  END IF;

  FOR m IN
    SELECT *
    FROM jsonb_array_elements(p_matches)
  LOOP

    INSERT INTO matches (matchday_id, category_id)
    VALUES (
      CASE (m->>'matchday')::int
        WHEN 1 THEN matchday1_id
        ELSE matchday2_id
      END,
      (m->>'category_id')::bigint
    )
    RETURNING id INTO match_id;

    INSERT INTO match_participants (
      match_id,
      player_id,
      substitute_id
    )
    SELECT
      match_id,
      jsonb_array_elements_text(m->'players')::bigint,
      NULL;

  END LOOP;

  UPDATE months
  SET status = 'confirmed'
  WHERE id = p_month_id;

END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_ascensor(p_month_id integer)
 RETURNS TABLE(category_id integer, category_name text, category_order integer, player_id integer, full_name text, nickname text, points integer, diff integer, games_for integer, matches_played integer)
 LANGUAGE sql
 STABLE
AS $function$
WITH sets_base AS (
  SELECT
    s.*,
    j.month_id,
    m.category_id,
    c.points_per_set,

    CASE
      WHEN p1.substitute_id IS NOT NULL THEN NULL
      ELSE s.pair1_player1_id
    END AS real_p1_j1,

    CASE
      WHEN p2.substitute_id IS NOT NULL THEN NULL
      ELSE s.pair1_player2_id
    END AS real_p1_j2,

    CASE
      WHEN p3.substitute_id IS NOT NULL THEN NULL
      ELSE s.pair2_player1_id
    END AS real_p2_j1,

    CASE
      WHEN p4.substitute_id IS NOT NULL THEN NULL
      ELSE s.pair2_player2_id
    END AS real_p2_j2

  FROM public.sets s
  JOIN public.matches m
    ON m.id = s.match_id

  JOIN public.matchdays j
    ON j.id = m.matchday_id

  JOIN public.categories c
    ON c.id = m.category_id

  LEFT JOIN public.match_participants p1
    ON p1.match_id = s.match_id
    AND p1.player_id = s.pair1_player1_id

  LEFT JOIN public.match_participants p2
    ON p2.match_id = s.match_id
    AND p2.player_id = s.pair1_player2_id

  LEFT JOIN public.match_participants p3
    ON p3.match_id = s.match_id
    AND p3.player_id = s.pair2_player1_id

  LEFT JOIN public.match_participants p4
    ON p4.match_id = s.match_id
    AND p4.player_id = s.pair2_player2_id
),

expanded_sets AS (
  SELECT
    match_id,
    month_id,
    category_id,
    points_per_set,
    real_p1_j1 AS player_id,
    pair1_score AS gf,
    pair2_score AS ga,
    (pair1_score > pair2_score) AS win
  FROM sets_base

  UNION ALL

  SELECT
    match_id,
    month_id,
    category_id,
    points_per_set,
    real_p1_j2,
    pair1_score,
    pair2_score,
    (pair1_score > pair2_score)
  FROM sets_base

  UNION ALL

  SELECT
    match_id,
    month_id,
    category_id,
    points_per_set,
    real_p2_j1,
    pair2_score,
    pair1_score,
    (pair2_score > pair1_score)
  FROM sets_base

  UNION ALL

  SELECT
    match_id,
    month_id,
    category_id,
    points_per_set,
    real_p2_j2,
    pair2_score,
    pair1_score,
    (pair2_score > pair1_score)
  FROM sets_base
),

classification AS (
  SELECT
    category_id,
    player_id,

    SUM(CASE WHEN win THEN points_per_set ELSE 0 END)
      + COUNT(DISTINCT match_id) * 5 AS points,

    SUM(gf - ga) AS diff,
    SUM(gf) AS games_for,

    COUNT(DISTINCT match_id) AS matches_played

  FROM expanded_sets
  WHERE month_id = p_month_id
    AND player_id IS NOT NULL
  GROUP BY category_id, player_id
),

players_in_categories AS (
  SELECT
    jcm.category_id AS category_id,
    jcm.player_id AS player_id,
    s.nickname,
    s.full_name
  FROM public.player_category_assignments jcm
  JOIN public.members s
    ON s.id = jcm.player_id
  WHERE jcm.month_id = p_month_id
)

SELECT
  cat.id AS category_id,
  cat.name AS category_name,
  cat.order AS category_order,
  p.player_id,
  p.full_name,
  p.nickname,
  COALESCE(c.points, 0) AS points,
  COALESCE(c.diff, 0) AS diff,
  COALESCE(c.games_for, 0) AS games_for,
  COALESCE(c.matches_played, 0) AS matches_played
FROM players_in_categories p
JOIN public.categories cat
  ON cat.id = p.category_id
LEFT JOIN classification c
  ON c.category_id = p.category_id
  AND c.player_id = p.player_id
ORDER BY
  cat.order,
  points DESC,
  diff DESC,
  games_for DESC;
$function$
;

CREATE OR REPLACE FUNCTION public.get_general_classification(p_season_id integer)
 RETURNS TABLE(player_id integer, full_name text, nickname text, points integer, diff integer, games_for integer, matches_played integer)
 LANGUAGE sql
 STABLE
AS $function$

WITH sets_base AS (
  SELECT
    s.*,
    m.category_id,
    c.points_per_set,
    mo.season_id,

    CASE
      WHEN p1.substitute_id IS NOT NULL THEN NULL
      ELSE s.pair1_player1_id
    END AS real_p1_j1,

    CASE
      WHEN p2.substitute_id IS NOT NULL THEN NULL
      ELSE s.pair1_player2_id
    END AS real_p1_j2,

    CASE
      WHEN p3.substitute_id IS NOT NULL THEN NULL
      ELSE s.pair2_player1_id
    END AS real_p2_j1,

    CASE
      WHEN p4.substitute_id IS NOT NULL THEN NULL
      ELSE s.pair2_player2_id
    END AS real_p2_j2

  FROM public.sets s
  JOIN public.matches m
    ON m.id = s.match_id
  JOIN public.matchdays j
    ON j.id = m.matchday_id
  JOIN public.months mo
    ON mo.id = j.month_id
  JOIN public.categories c
    ON c.id = m.category_id

  LEFT JOIN public.match_participants p1
    ON p1.match_id = s.match_id
    AND p1.player_id = s.pair1_player1_id

  LEFT JOIN public.match_participants p2
    ON p2.match_id = s.match_id
    AND p2.player_id = s.pair1_player2_id

  LEFT JOIN public.match_participants p3
    ON p3.match_id = s.match_id
    AND p3.player_id = s.pair2_player1_id

  LEFT JOIN public.match_participants p4
    ON p4.match_id = s.match_id
    AND p4.player_id = s.pair2_player2_id

  WHERE mo.season_id = p_season_id
),

expanded_sets AS (
  SELECT
    match_id,
    category_id,
    points_per_set,
    real_p1_j1 AS player_id,
    pair1_score AS gf,
    pair2_score AS ga,
    (pair1_score > pair2_score) AS win
  FROM sets_base

  UNION ALL

  SELECT
    match_id,
    category_id,
    points_per_set,
    real_p1_j2,
    pair1_score,
    pair2_score,
    (pair1_score > pair2_score)
  FROM sets_base

  UNION ALL

  SELECT
    match_id,
    category_id,
    points_per_set,
    real_p2_j1,
    pair2_score,
    pair1_score,
    (pair2_score > pair1_score)
  FROM sets_base

  UNION ALL

  SELECT
    match_id,
    category_id,
    points_per_set,
    real_p2_j2,
    pair2_score,
    pair1_score,
    (pair2_score > pair1_score)
  FROM sets_base
),

classification AS (
  SELECT
    player_id,
    SUM(CASE WHEN win THEN points_per_set ELSE 0 END)
      + COUNT(DISTINCT match_id) * 5 AS base_points,
    SUM(gf - ga) AS diff,
    SUM(gf) AS games_for,
    COUNT(DISTINCT match_id) AS matches_played
  FROM expanded_sets
  WHERE player_id IS NOT NULL
  GROUP BY player_id
),

bonus AS (
  SELECT
    b.player_id,
    SUM(b.quantity) AS bonus_points
  FROM public.bonuses b
  WHERE b.month_id IN (
    SELECT mo.id
    FROM public.months mo
    WHERE mo.season_id = p_season_id
  )
  GROUP BY b.player_id
)

SELECT
  c.player_id,
  s.full_name,
  s.nickname,
  (c.base_points + COALESCE(b.bonus_points, 0)) AS points,
  c.diff,
  c.games_for,
  c.matches_played

FROM classification c
JOIN public.members s
  ON s.id = c.player_id

LEFT JOIN bonus b
  ON b.player_id = c.player_id

ORDER BY
  (c.base_points + COALESCE(b.bonus_points, 0)) DESC,
  c.diff DESC,
  c.games_for DESC;

$function$
;

CREATE OR REPLACE FUNCTION public.register_match_results(p_match_id integer, p_sets jsonb, p_participation jsonb)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  DELETE FROM public.sets
  WHERE match_id = p_match_id;

  INSERT INTO public.sets (
    match_id,
    "order",
    pair1_player1_id,
    pair1_player2_id,
    pair2_player1_id,
    pair2_player2_id,
    pair1_score,
    pair2_score
  )
  SELECT
    p_match_id,
    (s->>'order')::int,
    (s->>'pair1_player1_id')::int,
    (s->>'pair1_player2_id')::int,
    (s->>'pair2_player1_id')::int,
    (s->>'pair2_player2_id')::int,
    (s->>'pair1_score')::int,
    (s->>'pair2_score')::int
  FROM jsonb_array_elements(p_sets) AS s;

  UPDATE public.match_participants
  SET substitute_id = NULL
  WHERE match_id = p_match_id;

  UPDATE public.match_participants AS mp
  SET substitute_id = data.substitute_id
  FROM (
    SELECT
      (p->>'player_id')::int AS player_id,
      (p->>'substitute_id')::int AS substitute_id
    FROM jsonb_array_elements(p_participation) AS p
  ) AS data
  WHERE mp.match_id = p_match_id
    AND mp.player_id = data.player_id;

END;
$function$
;

CREATE OR REPLACE FUNCTION public.save_month_assignments(p_month_id bigint, p_assignments jsonb)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_status text;
BEGIN

  SELECT status INTO v_status
  FROM months
  WHERE id = p_month_id;

  IF v_status IS NULL THEN
    RAISE EXCEPTION 'Mes no encontrado';
  END IF;

  IF v_status = 'locked' THEN
    RAISE EXCEPTION 'El mes está cerrado y no se puede editar.';
  END IF;

  DELETE FROM player_category_assignments
  WHERE month_id = p_month_id;

  INSERT INTO player_category_assignments (month_id, player_id, category_id)
  SELECT
    p_month_id,
    (a->>'player_id')::bigint,
    (a->>'category_id')::bigint
  FROM jsonb_array_elements(p_assignments) AS a;

END;
$function$
;

grant delete on table "public"."bonuses" to "anon";

grant insert on table "public"."bonuses" to "anon";

grant references on table "public"."bonuses" to "anon";

grant select on table "public"."bonuses" to "anon";

grant trigger on table "public"."bonuses" to "anon";

grant truncate on table "public"."bonuses" to "anon";

grant update on table "public"."bonuses" to "anon";

grant delete on table "public"."bonuses" to "authenticated";

grant insert on table "public"."bonuses" to "authenticated";

grant references on table "public"."bonuses" to "authenticated";

grant select on table "public"."bonuses" to "authenticated";

grant trigger on table "public"."bonuses" to "authenticated";

grant truncate on table "public"."bonuses" to "authenticated";

grant update on table "public"."bonuses" to "authenticated";

grant delete on table "public"."bonuses" to "service_role";

grant insert on table "public"."bonuses" to "service_role";

grant references on table "public"."bonuses" to "service_role";

grant select on table "public"."bonuses" to "service_role";

grant trigger on table "public"."bonuses" to "service_role";

grant truncate on table "public"."bonuses" to "service_role";

grant update on table "public"."bonuses" to "service_role";

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";

grant delete on table "public"."inscriptions" to "anon";

grant insert on table "public"."inscriptions" to "anon";

grant references on table "public"."inscriptions" to "anon";

grant select on table "public"."inscriptions" to "anon";

grant trigger on table "public"."inscriptions" to "anon";

grant truncate on table "public"."inscriptions" to "anon";

grant update on table "public"."inscriptions" to "anon";

grant delete on table "public"."inscriptions" to "authenticated";

grant insert on table "public"."inscriptions" to "authenticated";

grant references on table "public"."inscriptions" to "authenticated";

grant select on table "public"."inscriptions" to "authenticated";

grant trigger on table "public"."inscriptions" to "authenticated";

grant truncate on table "public"."inscriptions" to "authenticated";

grant update on table "public"."inscriptions" to "authenticated";

grant delete on table "public"."inscriptions" to "service_role";

grant insert on table "public"."inscriptions" to "service_role";

grant references on table "public"."inscriptions" to "service_role";

grant select on table "public"."inscriptions" to "service_role";

grant trigger on table "public"."inscriptions" to "service_role";

grant truncate on table "public"."inscriptions" to "service_role";

grant update on table "public"."inscriptions" to "service_role";

grant delete on table "public"."match_participants" to "anon";

grant insert on table "public"."match_participants" to "anon";

grant references on table "public"."match_participants" to "anon";

grant select on table "public"."match_participants" to "anon";

grant trigger on table "public"."match_participants" to "anon";

grant truncate on table "public"."match_participants" to "anon";

grant update on table "public"."match_participants" to "anon";

grant delete on table "public"."match_participants" to "authenticated";

grant insert on table "public"."match_participants" to "authenticated";

grant references on table "public"."match_participants" to "authenticated";

grant select on table "public"."match_participants" to "authenticated";

grant trigger on table "public"."match_participants" to "authenticated";

grant truncate on table "public"."match_participants" to "authenticated";

grant update on table "public"."match_participants" to "authenticated";

grant delete on table "public"."match_participants" to "service_role";

grant insert on table "public"."match_participants" to "service_role";

grant references on table "public"."match_participants" to "service_role";

grant select on table "public"."match_participants" to "service_role";

grant trigger on table "public"."match_participants" to "service_role";

grant truncate on table "public"."match_participants" to "service_role";

grant update on table "public"."match_participants" to "service_role";

grant delete on table "public"."matchdays" to "anon";

grant insert on table "public"."matchdays" to "anon";

grant references on table "public"."matchdays" to "anon";

grant select on table "public"."matchdays" to "anon";

grant trigger on table "public"."matchdays" to "anon";

grant truncate on table "public"."matchdays" to "anon";

grant update on table "public"."matchdays" to "anon";

grant delete on table "public"."matchdays" to "authenticated";

grant insert on table "public"."matchdays" to "authenticated";

grant references on table "public"."matchdays" to "authenticated";

grant select on table "public"."matchdays" to "authenticated";

grant trigger on table "public"."matchdays" to "authenticated";

grant truncate on table "public"."matchdays" to "authenticated";

grant update on table "public"."matchdays" to "authenticated";

grant delete on table "public"."matchdays" to "service_role";

grant insert on table "public"."matchdays" to "service_role";

grant references on table "public"."matchdays" to "service_role";

grant select on table "public"."matchdays" to "service_role";

grant trigger on table "public"."matchdays" to "service_role";

grant truncate on table "public"."matchdays" to "service_role";

grant update on table "public"."matchdays" to "service_role";

grant delete on table "public"."matches" to "anon";

grant insert on table "public"."matches" to "anon";

grant references on table "public"."matches" to "anon";

grant select on table "public"."matches" to "anon";

grant trigger on table "public"."matches" to "anon";

grant truncate on table "public"."matches" to "anon";

grant update on table "public"."matches" to "anon";

grant delete on table "public"."matches" to "authenticated";

grant insert on table "public"."matches" to "authenticated";

grant references on table "public"."matches" to "authenticated";

grant select on table "public"."matches" to "authenticated";

grant trigger on table "public"."matches" to "authenticated";

grant truncate on table "public"."matches" to "authenticated";

grant update on table "public"."matches" to "authenticated";

grant delete on table "public"."matches" to "service_role";

grant insert on table "public"."matches" to "service_role";

grant references on table "public"."matches" to "service_role";

grant select on table "public"."matches" to "service_role";

grant trigger on table "public"."matches" to "service_role";

grant truncate on table "public"."matches" to "service_role";

grant update on table "public"."matches" to "service_role";

grant delete on table "public"."members" to "anon";

grant insert on table "public"."members" to "anon";

grant references on table "public"."members" to "anon";

grant select on table "public"."members" to "anon";

grant trigger on table "public"."members" to "anon";

grant truncate on table "public"."members" to "anon";

grant update on table "public"."members" to "anon";

grant delete on table "public"."members" to "authenticated";

grant insert on table "public"."members" to "authenticated";

grant references on table "public"."members" to "authenticated";

grant select on table "public"."members" to "authenticated";

grant trigger on table "public"."members" to "authenticated";

grant truncate on table "public"."members" to "authenticated";

grant update on table "public"."members" to "authenticated";

grant delete on table "public"."members" to "service_role";

grant insert on table "public"."members" to "service_role";

grant references on table "public"."members" to "service_role";

grant select on table "public"."members" to "service_role";

grant trigger on table "public"."members" to "service_role";

grant truncate on table "public"."members" to "service_role";

grant update on table "public"."members" to "service_role";

grant delete on table "public"."months" to "anon";

grant insert on table "public"."months" to "anon";

grant references on table "public"."months" to "anon";

grant select on table "public"."months" to "anon";

grant trigger on table "public"."months" to "anon";

grant truncate on table "public"."months" to "anon";

grant update on table "public"."months" to "anon";

grant delete on table "public"."months" to "authenticated";

grant insert on table "public"."months" to "authenticated";

grant references on table "public"."months" to "authenticated";

grant select on table "public"."months" to "authenticated";

grant trigger on table "public"."months" to "authenticated";

grant truncate on table "public"."months" to "authenticated";

grant update on table "public"."months" to "authenticated";

grant delete on table "public"."months" to "service_role";

grant insert on table "public"."months" to "service_role";

grant references on table "public"."months" to "service_role";

grant select on table "public"."months" to "service_role";

grant trigger on table "public"."months" to "service_role";

grant truncate on table "public"."months" to "service_role";

grant update on table "public"."months" to "service_role";

grant delete on table "public"."player_category_assignments" to "anon";

grant insert on table "public"."player_category_assignments" to "anon";

grant references on table "public"."player_category_assignments" to "anon";

grant select on table "public"."player_category_assignments" to "anon";

grant trigger on table "public"."player_category_assignments" to "anon";

grant truncate on table "public"."player_category_assignments" to "anon";

grant update on table "public"."player_category_assignments" to "anon";

grant delete on table "public"."player_category_assignments" to "authenticated";

grant insert on table "public"."player_category_assignments" to "authenticated";

grant references on table "public"."player_category_assignments" to "authenticated";

grant select on table "public"."player_category_assignments" to "authenticated";

grant trigger on table "public"."player_category_assignments" to "authenticated";

grant truncate on table "public"."player_category_assignments" to "authenticated";

grant update on table "public"."player_category_assignments" to "authenticated";

grant delete on table "public"."player_category_assignments" to "service_role";

grant insert on table "public"."player_category_assignments" to "service_role";

grant references on table "public"."player_category_assignments" to "service_role";

grant select on table "public"."player_category_assignments" to "service_role";

grant trigger on table "public"."player_category_assignments" to "service_role";

grant truncate on table "public"."player_category_assignments" to "service_role";

grant update on table "public"."player_category_assignments" to "service_role";

grant delete on table "public"."seasons" to "anon";

grant insert on table "public"."seasons" to "anon";

grant references on table "public"."seasons" to "anon";

grant select on table "public"."seasons" to "anon";

grant trigger on table "public"."seasons" to "anon";

grant truncate on table "public"."seasons" to "anon";

grant update on table "public"."seasons" to "anon";

grant delete on table "public"."seasons" to "authenticated";

grant insert on table "public"."seasons" to "authenticated";

grant references on table "public"."seasons" to "authenticated";

grant select on table "public"."seasons" to "authenticated";

grant trigger on table "public"."seasons" to "authenticated";

grant truncate on table "public"."seasons" to "authenticated";

grant update on table "public"."seasons" to "authenticated";

grant delete on table "public"."seasons" to "service_role";

grant insert on table "public"."seasons" to "service_role";

grant references on table "public"."seasons" to "service_role";

grant select on table "public"."seasons" to "service_role";

grant trigger on table "public"."seasons" to "service_role";

grant truncate on table "public"."seasons" to "service_role";

grant update on table "public"."seasons" to "service_role";

grant delete on table "public"."sets" to "anon";

grant insert on table "public"."sets" to "anon";

grant references on table "public"."sets" to "anon";

grant select on table "public"."sets" to "anon";

grant trigger on table "public"."sets" to "anon";

grant truncate on table "public"."sets" to "anon";

grant update on table "public"."sets" to "anon";

grant delete on table "public"."sets" to "authenticated";

grant insert on table "public"."sets" to "authenticated";

grant references on table "public"."sets" to "authenticated";

grant select on table "public"."sets" to "authenticated";

grant trigger on table "public"."sets" to "authenticated";

grant truncate on table "public"."sets" to "authenticated";

grant update on table "public"."sets" to "authenticated";

grant delete on table "public"."sets" to "service_role";

grant insert on table "public"."sets" to "service_role";

grant references on table "public"."sets" to "service_role";

grant select on table "public"."sets" to "service_role";

grant trigger on table "public"."sets" to "service_role";

grant truncate on table "public"."sets" to "service_role";

grant update on table "public"."sets" to "service_role";

grant delete on table "public"."tournaments" to "anon";

grant insert on table "public"."tournaments" to "anon";

grant references on table "public"."tournaments" to "anon";

grant select on table "public"."tournaments" to "anon";

grant trigger on table "public"."tournaments" to "anon";

grant truncate on table "public"."tournaments" to "anon";

grant update on table "public"."tournaments" to "anon";

grant delete on table "public"."tournaments" to "authenticated";

grant insert on table "public"."tournaments" to "authenticated";

grant references on table "public"."tournaments" to "authenticated";

grant select on table "public"."tournaments" to "authenticated";

grant trigger on table "public"."tournaments" to "authenticated";

grant truncate on table "public"."tournaments" to "authenticated";

grant update on table "public"."tournaments" to "authenticated";

grant delete on table "public"."tournaments" to "service_role";

grant insert on table "public"."tournaments" to "service_role";

grant references on table "public"."tournaments" to "service_role";

grant select on table "public"."tournaments" to "service_role";

grant trigger on table "public"."tournaments" to "service_role";

grant truncate on table "public"."tournaments" to "service_role";

grant update on table "public"."tournaments" to "service_role";


  create policy "Admin can do anything"
  on "public"."bonuses"
  as permissive
  for all
  to public
using (((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true));



  create policy "Enable read access for all users"
  on "public"."bonuses"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."categories"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for authenticated users only"
  on "public"."inscriptions"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "Only if not manually closed"
  on "public"."inscriptions"
  as restrictive
  for insert
  to public
with check ((EXISTS ( SELECT 1
   FROM public.tournaments t
  WHERE ((t.id = inscriptions.tournament_id) AND (t.manually_closed = false)))));



  create policy "Only within date"
  on "public"."inscriptions"
  as restrictive
  for insert
  to public
with check ((EXISTS ( SELECT 1
   FROM public.tournaments t
  WHERE ((t.id = inscriptions.tournament_id) AND (now() < t.inscription_end_date)))));



  create policy "Admins can do ANYTHING"
  on "public"."match_participants"
  as permissive
  for all
  to public
using (((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true));



  create policy "Enable read access for all users"
  on "public"."match_participants"
  as permissive
  for select
  to public
using (true);



  create policy "Admins can do ANYTHING"
  on "public"."matchdays"
  as permissive
  for all
  to public
using (((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true));



  create policy "Enable read access for all users"
  on "public"."matchdays"
  as permissive
  for select
  to public
using (true);



  create policy "Admins can do ANYTHING"
  on "public"."matches"
  as permissive
  for all
  to public
using (((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true));



  create policy "Enable read access for all users"
  on "public"."matches"
  as permissive
  for select
  to public
using (true);



  create policy "Admins can do ANYTHING"
  on "public"."members"
  as permissive
  for all
  to public
using (((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true));



  create policy "Everyone can SELECT"
  on "public"."members"
  as permissive
  for select
  to public
using (true);



  create policy "Admin can do anything"
  on "public"."months"
  as permissive
  for all
  to public
using (((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true));



  create policy "Enable read access for all users"
  on "public"."months"
  as permissive
  for select
  to public
using (true);



  create policy "Admins can do ANYTHING"
  on "public"."player_category_assignments"
  as permissive
  for all
  to public
using (((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true));



  create policy "Enable read access for all users"
  on "public"."player_category_assignments"
  as permissive
  for select
  to public
using (true);



  create policy "Admin can do ANYTHING"
  on "public"."seasons"
  as permissive
  for all
  to public
using (((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true));



  create policy "Anyone can read"
  on "public"."seasons"
  as permissive
  for select
  to public
using (true);



  create policy "Admins can do ANYTHING"
  on "public"."sets"
  as permissive
  for all
  to public
using (((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true));



  create policy "Enable read access for all users"
  on "public"."sets"
  as permissive
  for select
  to public
using (true);



  create policy "Admin can do ANYTHING"
  on "public"."tournaments"
  as permissive
  for all
  to public
using (((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true));



  create policy "Everyone can read"
  on "public"."tournaments"
  as permissive
  for select
  to public
using (true);

insert into storage.buckets (id, name, public)
values ('torneos', 'torneos', true)
on conflict (id) do nothing;

  create policy "Admins can do ANYTHING 1g80m2a_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using (((bucket_id = 'torneos'::text) AND ((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true)));



  create policy "Admins can do ANYTHING 1g80m2a_1"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'torneos'::text) AND ((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true)));



  create policy "Admins can do ANYTHING 1g80m2a_2"
  on "storage"."objects"
  as permissive
  for update
  to public
using (((bucket_id = 'torneos'::text) AND ((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true)));



  create policy "Admins can do ANYTHING 1g80m2a_3"
  on "storage"."objects"
  as permissive
  for delete
  to public
using (((bucket_id = 'torneos'::text) AND ((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true)));

insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do nothing;


