
  create table "public"."Inscripciones" (
    "id" bigint generated by default as identity not null,
    "torneo_id" bigint,
    "user_id" uuid,
    "phone_number" text
      );


alter table "public"."Inscripciones" enable row level security;

CREATE UNIQUE INDEX inscripciones_pkey ON public."Inscripciones" USING btree (id);

CREATE UNIQUE INDEX inscripciones_torneo_user_unique ON public."Inscripciones" USING btree (torneo_id, user_id);

alter table "public"."Inscripciones" add constraint "inscripciones_pkey" PRIMARY KEY using index "inscripciones_pkey";

alter table "public"."Inscripciones" add constraint "inscripciones_torneo_id_fkey" FOREIGN KEY (torneo_id) REFERENCES public."Torneos"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Inscripciones" validate constraint "inscripciones_torneo_id_fkey";

alter table "public"."Inscripciones" add constraint "inscripciones_torneo_user_unique" UNIQUE using index "inscripciones_torneo_user_unique";

alter table "public"."Inscripciones" add constraint "inscripciones_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Inscripciones" validate constraint "inscripciones_user_id_fkey";

grant delete on table "public"."Inscripciones" to "anon";

grant insert on table "public"."Inscripciones" to "anon";

grant references on table "public"."Inscripciones" to "anon";

grant select on table "public"."Inscripciones" to "anon";

grant trigger on table "public"."Inscripciones" to "anon";

grant truncate on table "public"."Inscripciones" to "anon";

grant update on table "public"."Inscripciones" to "anon";

grant delete on table "public"."Inscripciones" to "authenticated";

grant insert on table "public"."Inscripciones" to "authenticated";

grant references on table "public"."Inscripciones" to "authenticated";

grant select on table "public"."Inscripciones" to "authenticated";

grant trigger on table "public"."Inscripciones" to "authenticated";

grant truncate on table "public"."Inscripciones" to "authenticated";

grant update on table "public"."Inscripciones" to "authenticated";

grant delete on table "public"."Inscripciones" to "postgres";

grant insert on table "public"."Inscripciones" to "postgres";

grant references on table "public"."Inscripciones" to "postgres";

grant select on table "public"."Inscripciones" to "postgres";

grant trigger on table "public"."Inscripciones" to "postgres";

grant truncate on table "public"."Inscripciones" to "postgres";

grant update on table "public"."Inscripciones" to "postgres";

grant delete on table "public"."Inscripciones" to "service_role";

grant insert on table "public"."Inscripciones" to "service_role";

grant references on table "public"."Inscripciones" to "service_role";

grant select on table "public"."Inscripciones" to "service_role";

grant trigger on table "public"."Inscripciones" to "service_role";

grant truncate on table "public"."Inscripciones" to "service_role";

grant update on table "public"."Inscripciones" to "service_role";


  create policy "Only authenticated users can INSERT"
  on "public"."Inscripciones"
  as permissive
  for insert
  to authenticated
with check (true);



