
  create table "public"."tournament_matches" (
    "id" bigint generated by default as identity not null,
    "tournament_id" bigint not null,
    "pair1" text[] not null,
    "pair2" text[] not null,
    "scheduled_datetime" timestamp with time zone not null,
    "category" text,
    "result" numeric[]
      );


alter table "public"."tournament_matches" enable row level security;

CREATE UNIQUE INDEX tournament_matches_pkey ON public.tournament_matches USING btree (id);

alter table "public"."tournament_matches" add constraint "tournament_matches_pkey" PRIMARY KEY using index "tournament_matches_pkey";

alter table "public"."tournament_matches" add constraint "tournament_matches_tournament_id_fkey" FOREIGN KEY (tournament_id) REFERENCES public.tournaments(id) ON DELETE CASCADE not valid;

alter table "public"."tournament_matches" validate constraint "tournament_matches_tournament_id_fkey";

grant references on table "public"."tournament_matches" to "anon";

grant trigger on table "public"."tournament_matches" to "anon";

grant truncate on table "public"."tournament_matches" to "anon";

grant references on table "public"."tournament_matches" to "authenticated";

grant trigger on table "public"."tournament_matches" to "authenticated";

grant truncate on table "public"."tournament_matches" to "authenticated";

grant references on table "public"."tournament_matches" to "service_role";

grant trigger on table "public"."tournament_matches" to "service_role";

grant truncate on table "public"."tournament_matches" to "service_role";


  create policy "Admins can do ANYTHING"
  on "public"."tournament_matches"
  as permissive
  for all
  to public
using (((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true));



