
  create table "public"."Bonus" (
    "id" bigint generated by default as identity not null,
    "player_id" bigint not null,
    "quantity" numeric not null default '0'::numeric,
    "mes_id" bigint
      );


alter table "public"."Bonus" enable row level security;

CREATE UNIQUE INDEX "Bonus_pkey" ON public."Bonus" USING btree (id);

alter table "public"."Bonus" add constraint "Bonus_pkey" PRIMARY KEY using index "Bonus_pkey";

alter table "public"."Bonus" add constraint "Bonus_mes_id_fkey" FOREIGN KEY (mes_id) REFERENCES public."Meses"(id) not valid;

alter table "public"."Bonus" validate constraint "Bonus_mes_id_fkey";

alter table "public"."Bonus" add constraint "Bonus_player_id_fkey" FOREIGN KEY (player_id) REFERENCES public."Socios"(id) not valid;

alter table "public"."Bonus" validate constraint "Bonus_player_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_global_classification(p_temporada_id integer)
 RETURNS TABLE(player_id integer, full_name text, nickname text, points integer, diff integer, games_for integer, matches_played integer)
 LANGUAGE sql
 STABLE
AS $function$

WITH sets_base AS (
  SELECT
    s.*,
    m.categoria_id,
    c.puntos_set,

    CASE
      WHEN p1.sustituto_id IS NOT NULL THEN NULL
      ELSE s.pareja1_jugador1_id
    END AS real_p1_j1,

    CASE
      WHEN p2.sustituto_id IS NOT NULL THEN NULL
      ELSE s.pareja1_jugador2_id
    END AS real_p1_j2,

    CASE
      WHEN p3.sustituto_id IS NOT NULL THEN NULL
      ELSE s.pareja2_jugador1_id
    END AS real_p2_j1,

    CASE
      WHEN p4.sustituto_id IS NOT NULL THEN NULL
      ELSE s.pareja2_jugador2_id
    END AS real_p2_j2

  FROM public."Sets" s
  JOIN public."Partidos" m
    ON m.id = s.partido_id
  JOIN public."Jornadas" jor
    ON jor.id = m.jornada_id
  JOIN public."Meses" mes
    ON mes.id = jor.mes_id
  JOIN public."Categorias" c
    ON c.id = m.categoria_id

  LEFT JOIN public."Participacion" p1
    ON p1.partido_id = s.partido_id
    AND p1.jugador_id = s.pareja1_jugador1_id

  LEFT JOIN public."Participacion" p2
    ON p2.partido_id = s.partido_id
    AND p2.jugador_id = s.pareja1_jugador2_id

  LEFT JOIN public."Participacion" p3
    ON p3.partido_id = s.partido_id
    AND p3.jugador_id = s.pareja2_jugador1_id

  LEFT JOIN public."Participacion" p4
    ON p4.partido_id = s.partido_id
    AND p4.jugador_id = s.pareja2_jugador2_id

  WHERE mes.temporada_id = p_temporada_id
),

expanded_sets AS (
  SELECT
    partido_id,
    categoria_id,
    puntos_set,
    real_p1_j1 AS player_id,
    pareja1_juegos AS gf,
    pareja2_juegos AS ga,
    (pareja1_juegos > pareja2_juegos) AS win
  FROM sets_base

  UNION ALL

  SELECT
    partido_id,
    categoria_id,
    puntos_set,
    real_p1_j2,
    pareja1_juegos,
    pareja2_juegos,
    (pareja1_juegos > pareja2_juegos)
  FROM sets_base

  UNION ALL

  SELECT
    partido_id,
    categoria_id,
    puntos_set,
    real_p2_j1,
    pareja2_juegos,
    pareja1_juegos,
    (pareja2_juegos > pareja1_juegos)
  FROM sets_base

  UNION ALL

  SELECT
    partido_id,
    categoria_id,
    puntos_set,
    real_p2_j2,
    pareja2_juegos,
    pareja1_juegos,
    (pareja2_juegos > pareja1_juegos)
  FROM sets_base
),

classification AS (
  SELECT
    player_id,
    SUM(CASE WHEN win THEN puntos_set ELSE 0 END)
      + COUNT(DISTINCT partido_id) * 5 AS base_points,
    SUM(gf - ga) AS diff,
    SUM(gf) AS games_for,
    COUNT(DISTINCT partido_id) AS matches_played
  FROM expanded_sets
  WHERE player_id IS NOT NULL
  GROUP BY player_id
),

bonus AS (
  SELECT
    b.player_id,
    SUM(b.quantity) AS bonus_points
  FROM public."Bonus" b
  WHERE b.mes_id IN (
    SELECT m.id
    FROM public."Meses" m
    WHERE m.temporada_id = p_temporada_id
  )
  GROUP BY b.player_id
)

SELECT
  c.player_id,
  s.full_name,
  s.nickname,
  (c.base_points + COALESCE(b.bonus_points, 0)) AS points,
  c.diff,
  c.games_for,
  c.matches_played

FROM classification c
JOIN public."Socios" s
  ON s.id = c.player_id

LEFT JOIN bonus b
  ON b.player_id = c.player_id

ORDER BY
  (c.base_points + COALESCE(b.bonus_points, 0)) DESC,
  c.diff DESC,
  c.games_for DESC;

$function$
;

grant delete on table "public"."Bonus" to "anon";

grant insert on table "public"."Bonus" to "anon";

grant references on table "public"."Bonus" to "anon";

grant select on table "public"."Bonus" to "anon";

grant trigger on table "public"."Bonus" to "anon";

grant truncate on table "public"."Bonus" to "anon";

grant update on table "public"."Bonus" to "anon";

grant delete on table "public"."Bonus" to "authenticated";

grant insert on table "public"."Bonus" to "authenticated";

grant references on table "public"."Bonus" to "authenticated";

grant select on table "public"."Bonus" to "authenticated";

grant trigger on table "public"."Bonus" to "authenticated";

grant truncate on table "public"."Bonus" to "authenticated";

grant update on table "public"."Bonus" to "authenticated";

grant delete on table "public"."Bonus" to "service_role";

grant insert on table "public"."Bonus" to "service_role";

grant references on table "public"."Bonus" to "service_role";

grant select on table "public"."Bonus" to "service_role";

grant trigger on table "public"."Bonus" to "service_role";

grant truncate on table "public"."Bonus" to "service_role";

grant update on table "public"."Bonus" to "service_role";


  create policy "Admin can do anything"
  on "public"."Bonus"
  as permissive
  for all
  to public
using (((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true));



  create policy "Enable read access for all users"
  on "public"."Bonus"
  as permissive
  for select
  to public
using (true);



  create policy "Admin can do anything"
  on "public"."Meses"
  as permissive
  for all
  to public
using (((((auth.jwt() -> 'app_metadata'::text) ->> 'admin'::text))::boolean = true));



