
  create table "public"."Categorias" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "order" numeric not null
      );


alter table "public"."Categorias" enable row level security;


  create table "public"."Jornadas" (
    "id" bigint generated by default as identity not null,
    "mes_id" bigint not null,
    "number" numeric not null
      );


alter table "public"."Jornadas" enable row level security;


  create table "public"."Jugador_Categoria_Mes" (
    "id" bigint generated by default as identity not null,
    "jugador_id" bigint not null,
    "mes_id" bigint not null,
    "categoria_id" bigint not null
      );


alter table "public"."Jugador_Categoria_Mes" enable row level security;


  create table "public"."Jugador_Partido" (
    "id" bigint generated by default as identity not null,
    "partido_id" bigint not null,
    "jugador_id" bigint not null
      );


alter table "public"."Jugador_Partido" enable row level security;


  create table "public"."Meses" (
    "id" bigint generated by default as identity not null,
    "temporada_id" bigint not null,
    "month" numeric not null
      );


alter table "public"."Meses" enable row level security;


  create table "public"."Partidos" (
    "id" bigint generated by default as identity not null,
    "jornada_id" bigint not null,
    "categoria_id" bigint not null
      );


alter table "public"."Partidos" enable row level security;

CREATE UNIQUE INDEX "Categorias_pkey" ON public."Categorias" USING btree (id);

CREATE UNIQUE INDEX "Jornadas_pkey" ON public."Jornadas" USING btree (id);

CREATE UNIQUE INDEX "Jugador_Categoria_Mes_pkey" ON public."Jugador_Categoria_Mes" USING btree (id);

CREATE UNIQUE INDEX "Jugador_Partido_pkey" ON public."Jugador_Partido" USING btree (id);

CREATE UNIQUE INDEX "Meses_pkey" ON public."Meses" USING btree (id);

CREATE UNIQUE INDEX "Partidos_pkey" ON public."Partidos" USING btree (id);

CREATE UNIQUE INDEX unique_category_per_month ON public."Jugador_Categoria_Mes" USING btree (mes_id, jugador_id);

CREATE UNIQUE INDEX unique_month ON public."Meses" USING btree (temporada_id, month);

CREATE UNIQUE INDEX unique_player_each_match ON public."Jugador_Partido" USING btree (partido_id, jugador_id);

alter table "public"."Categorias" add constraint "Categorias_pkey" PRIMARY KEY using index "Categorias_pkey";

alter table "public"."Jornadas" add constraint "Jornadas_pkey" PRIMARY KEY using index "Jornadas_pkey";

alter table "public"."Jugador_Categoria_Mes" add constraint "Jugador_Categoria_Mes_pkey" PRIMARY KEY using index "Jugador_Categoria_Mes_pkey";

alter table "public"."Jugador_Partido" add constraint "Jugador_Partido_pkey" PRIMARY KEY using index "Jugador_Partido_pkey";

alter table "public"."Meses" add constraint "Meses_pkey" PRIMARY KEY using index "Meses_pkey";

alter table "public"."Partidos" add constraint "Partidos_pkey" PRIMARY KEY using index "Partidos_pkey";

alter table "public"."Jornadas" add constraint "Jornadas_mes_id_fkey" FOREIGN KEY (mes_id) REFERENCES public."Meses"(id) not valid;

alter table "public"."Jornadas" validate constraint "Jornadas_mes_id_fkey";

alter table "public"."Jugador_Categoria_Mes" add constraint "Jugador_Categoria_Mes_categoria_id_fkey" FOREIGN KEY (categoria_id) REFERENCES public."Categorias"(id) not valid;

alter table "public"."Jugador_Categoria_Mes" validate constraint "Jugador_Categoria_Mes_categoria_id_fkey";

alter table "public"."Jugador_Categoria_Mes" add constraint "Jugador_Categoria_Mes_jugador_id_fkey" FOREIGN KEY (jugador_id) REFERENCES public."Socios"(id) not valid;

alter table "public"."Jugador_Categoria_Mes" validate constraint "Jugador_Categoria_Mes_jugador_id_fkey";

alter table "public"."Jugador_Categoria_Mes" add constraint "Jugador_Categoria_Mes_mes_id_fkey" FOREIGN KEY (mes_id) REFERENCES public."Meses"(id) not valid;

alter table "public"."Jugador_Categoria_Mes" validate constraint "Jugador_Categoria_Mes_mes_id_fkey";

alter table "public"."Jugador_Categoria_Mes" add constraint "unique_category_per_month" UNIQUE using index "unique_category_per_month";

alter table "public"."Jugador_Partido" add constraint "Jugador_Partido_jugador_id_fkey" FOREIGN KEY (jugador_id) REFERENCES public."Socios"(id) not valid;

alter table "public"."Jugador_Partido" validate constraint "Jugador_Partido_jugador_id_fkey";

alter table "public"."Jugador_Partido" add constraint "Jugador_Partido_partido_id_fkey" FOREIGN KEY (partido_id) REFERENCES public."Partidos"(id) not valid;

alter table "public"."Jugador_Partido" validate constraint "Jugador_Partido_partido_id_fkey";

alter table "public"."Jugador_Partido" add constraint "unique_player_each_match" UNIQUE using index "unique_player_each_match";

alter table "public"."Meses" add constraint "Meses_temporada_id_fkey" FOREIGN KEY (temporada_id) REFERENCES public."Temporadas"(id) not valid;

alter table "public"."Meses" validate constraint "Meses_temporada_id_fkey";

alter table "public"."Meses" add constraint "unique_month" UNIQUE using index "unique_month";

alter table "public"."Partidos" add constraint "Partidos_categoria_id_fkey" FOREIGN KEY (categoria_id) REFERENCES public."Categorias"(id) not valid;

alter table "public"."Partidos" validate constraint "Partidos_categoria_id_fkey";

alter table "public"."Partidos" add constraint "Partidos_jornada_id_fkey" FOREIGN KEY (jornada_id) REFERENCES public."Jornadas"(id) not valid;

alter table "public"."Partidos" validate constraint "Partidos_jornada_id_fkey";

grant delete on table "public"."Categorias" to "anon";

grant insert on table "public"."Categorias" to "anon";

grant references on table "public"."Categorias" to "anon";

grant select on table "public"."Categorias" to "anon";

grant trigger on table "public"."Categorias" to "anon";

grant truncate on table "public"."Categorias" to "anon";

grant update on table "public"."Categorias" to "anon";

grant delete on table "public"."Categorias" to "authenticated";

grant insert on table "public"."Categorias" to "authenticated";

grant references on table "public"."Categorias" to "authenticated";

grant select on table "public"."Categorias" to "authenticated";

grant trigger on table "public"."Categorias" to "authenticated";

grant truncate on table "public"."Categorias" to "authenticated";

grant update on table "public"."Categorias" to "authenticated";

grant delete on table "public"."Categorias" to "postgres";

grant insert on table "public"."Categorias" to "postgres";

grant references on table "public"."Categorias" to "postgres";

grant select on table "public"."Categorias" to "postgres";

grant trigger on table "public"."Categorias" to "postgres";

grant truncate on table "public"."Categorias" to "postgres";

grant update on table "public"."Categorias" to "postgres";

grant delete on table "public"."Categorias" to "service_role";

grant insert on table "public"."Categorias" to "service_role";

grant references on table "public"."Categorias" to "service_role";

grant select on table "public"."Categorias" to "service_role";

grant trigger on table "public"."Categorias" to "service_role";

grant truncate on table "public"."Categorias" to "service_role";

grant update on table "public"."Categorias" to "service_role";

grant delete on table "public"."Jornadas" to "anon";

grant insert on table "public"."Jornadas" to "anon";

grant references on table "public"."Jornadas" to "anon";

grant select on table "public"."Jornadas" to "anon";

grant trigger on table "public"."Jornadas" to "anon";

grant truncate on table "public"."Jornadas" to "anon";

grant update on table "public"."Jornadas" to "anon";

grant delete on table "public"."Jornadas" to "authenticated";

grant insert on table "public"."Jornadas" to "authenticated";

grant references on table "public"."Jornadas" to "authenticated";

grant select on table "public"."Jornadas" to "authenticated";

grant trigger on table "public"."Jornadas" to "authenticated";

grant truncate on table "public"."Jornadas" to "authenticated";

grant update on table "public"."Jornadas" to "authenticated";

grant delete on table "public"."Jornadas" to "postgres";

grant insert on table "public"."Jornadas" to "postgres";

grant references on table "public"."Jornadas" to "postgres";

grant select on table "public"."Jornadas" to "postgres";

grant trigger on table "public"."Jornadas" to "postgres";

grant truncate on table "public"."Jornadas" to "postgres";

grant update on table "public"."Jornadas" to "postgres";

grant delete on table "public"."Jornadas" to "service_role";

grant insert on table "public"."Jornadas" to "service_role";

grant references on table "public"."Jornadas" to "service_role";

grant select on table "public"."Jornadas" to "service_role";

grant trigger on table "public"."Jornadas" to "service_role";

grant truncate on table "public"."Jornadas" to "service_role";

grant update on table "public"."Jornadas" to "service_role";

grant delete on table "public"."Jugador_Categoria_Mes" to "anon";

grant insert on table "public"."Jugador_Categoria_Mes" to "anon";

grant references on table "public"."Jugador_Categoria_Mes" to "anon";

grant select on table "public"."Jugador_Categoria_Mes" to "anon";

grant trigger on table "public"."Jugador_Categoria_Mes" to "anon";

grant truncate on table "public"."Jugador_Categoria_Mes" to "anon";

grant update on table "public"."Jugador_Categoria_Mes" to "anon";

grant delete on table "public"."Jugador_Categoria_Mes" to "authenticated";

grant insert on table "public"."Jugador_Categoria_Mes" to "authenticated";

grant references on table "public"."Jugador_Categoria_Mes" to "authenticated";

grant select on table "public"."Jugador_Categoria_Mes" to "authenticated";

grant trigger on table "public"."Jugador_Categoria_Mes" to "authenticated";

grant truncate on table "public"."Jugador_Categoria_Mes" to "authenticated";

grant update on table "public"."Jugador_Categoria_Mes" to "authenticated";

grant delete on table "public"."Jugador_Categoria_Mes" to "postgres";

grant insert on table "public"."Jugador_Categoria_Mes" to "postgres";

grant references on table "public"."Jugador_Categoria_Mes" to "postgres";

grant select on table "public"."Jugador_Categoria_Mes" to "postgres";

grant trigger on table "public"."Jugador_Categoria_Mes" to "postgres";

grant truncate on table "public"."Jugador_Categoria_Mes" to "postgres";

grant update on table "public"."Jugador_Categoria_Mes" to "postgres";

grant delete on table "public"."Jugador_Categoria_Mes" to "service_role";

grant insert on table "public"."Jugador_Categoria_Mes" to "service_role";

grant references on table "public"."Jugador_Categoria_Mes" to "service_role";

grant select on table "public"."Jugador_Categoria_Mes" to "service_role";

grant trigger on table "public"."Jugador_Categoria_Mes" to "service_role";

grant truncate on table "public"."Jugador_Categoria_Mes" to "service_role";

grant update on table "public"."Jugador_Categoria_Mes" to "service_role";

grant delete on table "public"."Jugador_Partido" to "anon";

grant insert on table "public"."Jugador_Partido" to "anon";

grant references on table "public"."Jugador_Partido" to "anon";

grant select on table "public"."Jugador_Partido" to "anon";

grant trigger on table "public"."Jugador_Partido" to "anon";

grant truncate on table "public"."Jugador_Partido" to "anon";

grant update on table "public"."Jugador_Partido" to "anon";

grant delete on table "public"."Jugador_Partido" to "authenticated";

grant insert on table "public"."Jugador_Partido" to "authenticated";

grant references on table "public"."Jugador_Partido" to "authenticated";

grant select on table "public"."Jugador_Partido" to "authenticated";

grant trigger on table "public"."Jugador_Partido" to "authenticated";

grant truncate on table "public"."Jugador_Partido" to "authenticated";

grant update on table "public"."Jugador_Partido" to "authenticated";

grant delete on table "public"."Jugador_Partido" to "postgres";

grant insert on table "public"."Jugador_Partido" to "postgres";

grant references on table "public"."Jugador_Partido" to "postgres";

grant select on table "public"."Jugador_Partido" to "postgres";

grant trigger on table "public"."Jugador_Partido" to "postgres";

grant truncate on table "public"."Jugador_Partido" to "postgres";

grant update on table "public"."Jugador_Partido" to "postgres";

grant delete on table "public"."Jugador_Partido" to "service_role";

grant insert on table "public"."Jugador_Partido" to "service_role";

grant references on table "public"."Jugador_Partido" to "service_role";

grant select on table "public"."Jugador_Partido" to "service_role";

grant trigger on table "public"."Jugador_Partido" to "service_role";

grant truncate on table "public"."Jugador_Partido" to "service_role";

grant update on table "public"."Jugador_Partido" to "service_role";

grant delete on table "public"."Meses" to "anon";

grant insert on table "public"."Meses" to "anon";

grant references on table "public"."Meses" to "anon";

grant select on table "public"."Meses" to "anon";

grant trigger on table "public"."Meses" to "anon";

grant truncate on table "public"."Meses" to "anon";

grant update on table "public"."Meses" to "anon";

grant delete on table "public"."Meses" to "authenticated";

grant insert on table "public"."Meses" to "authenticated";

grant references on table "public"."Meses" to "authenticated";

grant select on table "public"."Meses" to "authenticated";

grant trigger on table "public"."Meses" to "authenticated";

grant truncate on table "public"."Meses" to "authenticated";

grant update on table "public"."Meses" to "authenticated";

grant delete on table "public"."Meses" to "postgres";

grant insert on table "public"."Meses" to "postgres";

grant references on table "public"."Meses" to "postgres";

grant select on table "public"."Meses" to "postgres";

grant trigger on table "public"."Meses" to "postgres";

grant truncate on table "public"."Meses" to "postgres";

grant update on table "public"."Meses" to "postgres";

grant delete on table "public"."Meses" to "service_role";

grant insert on table "public"."Meses" to "service_role";

grant references on table "public"."Meses" to "service_role";

grant select on table "public"."Meses" to "service_role";

grant trigger on table "public"."Meses" to "service_role";

grant truncate on table "public"."Meses" to "service_role";

grant update on table "public"."Meses" to "service_role";

grant delete on table "public"."Partidos" to "anon";

grant insert on table "public"."Partidos" to "anon";

grant references on table "public"."Partidos" to "anon";

grant select on table "public"."Partidos" to "anon";

grant trigger on table "public"."Partidos" to "anon";

grant truncate on table "public"."Partidos" to "anon";

grant update on table "public"."Partidos" to "anon";

grant delete on table "public"."Partidos" to "authenticated";

grant insert on table "public"."Partidos" to "authenticated";

grant references on table "public"."Partidos" to "authenticated";

grant select on table "public"."Partidos" to "authenticated";

grant trigger on table "public"."Partidos" to "authenticated";

grant truncate on table "public"."Partidos" to "authenticated";

grant update on table "public"."Partidos" to "authenticated";

grant delete on table "public"."Partidos" to "postgres";

grant insert on table "public"."Partidos" to "postgres";

grant references on table "public"."Partidos" to "postgres";

grant select on table "public"."Partidos" to "postgres";

grant trigger on table "public"."Partidos" to "postgres";

grant truncate on table "public"."Partidos" to "postgres";

grant update on table "public"."Partidos" to "postgres";

grant delete on table "public"."Partidos" to "service_role";

grant insert on table "public"."Partidos" to "service_role";

grant references on table "public"."Partidos" to "service_role";

grant select on table "public"."Partidos" to "service_role";

grant trigger on table "public"."Partidos" to "service_role";

grant truncate on table "public"."Partidos" to "service_role";

grant update on table "public"."Partidos" to "service_role";


