
  create table "public"."Socios" (
    "id" bigint generated by default as identity not null,
    "email" character varying,
    "name" character varying,
    "user_id" uuid
      );


alter table "public"."Socios" enable row level security;


  create table "public"."Temporadas" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null
      );


alter table "public"."Temporadas" enable row level security;


  create table "public"."Torneos" (
    "id" bigint generated by default as identity not null,
    "name" character varying,
    "description" text,
    "start_date" timestamp without time zone
      );


alter table "public"."Torneos" enable row level security;

CREATE UNIQUE INDEX "Socios_email_key" ON public."Socios" USING btree (email);

CREATE UNIQUE INDEX "Socios_pkey" ON public."Socios" USING btree (id);

CREATE UNIQUE INDEX "Socios_user_id_key" ON public."Socios" USING btree (user_id);

CREATE UNIQUE INDEX "Temporadas_pkey" ON public."Temporadas" USING btree (id);

CREATE UNIQUE INDEX "Torneos_pkey" ON public."Torneos" USING btree (id);

alter table "public"."Socios" add constraint "Socios_pkey" PRIMARY KEY using index "Socios_pkey";

alter table "public"."Temporadas" add constraint "Temporadas_pkey" PRIMARY KEY using index "Temporadas_pkey";

alter table "public"."Torneos" add constraint "Torneos_pkey" PRIMARY KEY using index "Torneos_pkey";

alter table "public"."Socios" add constraint "Socios_email_key" UNIQUE using index "Socios_email_key";

alter table "public"."Socios" add constraint "Socios_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."Socios" validate constraint "Socios_user_id_fkey";

alter table "public"."Socios" add constraint "Socios_user_id_key" UNIQUE using index "Socios_user_id_key";

grant delete on table "public"."Socios" to "anon";

grant insert on table "public"."Socios" to "anon";

grant references on table "public"."Socios" to "anon";

grant select on table "public"."Socios" to "anon";

grant trigger on table "public"."Socios" to "anon";

grant truncate on table "public"."Socios" to "anon";

grant update on table "public"."Socios" to "anon";

grant delete on table "public"."Socios" to "authenticated";

grant insert on table "public"."Socios" to "authenticated";

grant references on table "public"."Socios" to "authenticated";

grant select on table "public"."Socios" to "authenticated";

grant trigger on table "public"."Socios" to "authenticated";

grant truncate on table "public"."Socios" to "authenticated";

grant update on table "public"."Socios" to "authenticated";

grant delete on table "public"."Socios" to "postgres";

grant insert on table "public"."Socios" to "postgres";

grant references on table "public"."Socios" to "postgres";

grant select on table "public"."Socios" to "postgres";

grant trigger on table "public"."Socios" to "postgres";

grant truncate on table "public"."Socios" to "postgres";

grant update on table "public"."Socios" to "postgres";

grant delete on table "public"."Socios" to "service_role";

grant insert on table "public"."Socios" to "service_role";

grant references on table "public"."Socios" to "service_role";

grant select on table "public"."Socios" to "service_role";

grant trigger on table "public"."Socios" to "service_role";

grant truncate on table "public"."Socios" to "service_role";

grant update on table "public"."Socios" to "service_role";

grant delete on table "public"."Temporadas" to "anon";

grant insert on table "public"."Temporadas" to "anon";

grant references on table "public"."Temporadas" to "anon";

grant select on table "public"."Temporadas" to "anon";

grant trigger on table "public"."Temporadas" to "anon";

grant truncate on table "public"."Temporadas" to "anon";

grant update on table "public"."Temporadas" to "anon";

grant delete on table "public"."Temporadas" to "authenticated";

grant insert on table "public"."Temporadas" to "authenticated";

grant references on table "public"."Temporadas" to "authenticated";

grant select on table "public"."Temporadas" to "authenticated";

grant trigger on table "public"."Temporadas" to "authenticated";

grant truncate on table "public"."Temporadas" to "authenticated";

grant update on table "public"."Temporadas" to "authenticated";

grant delete on table "public"."Temporadas" to "postgres";

grant insert on table "public"."Temporadas" to "postgres";

grant references on table "public"."Temporadas" to "postgres";

grant select on table "public"."Temporadas" to "postgres";

grant trigger on table "public"."Temporadas" to "postgres";

grant truncate on table "public"."Temporadas" to "postgres";

grant update on table "public"."Temporadas" to "postgres";

grant delete on table "public"."Temporadas" to "service_role";

grant insert on table "public"."Temporadas" to "service_role";

grant references on table "public"."Temporadas" to "service_role";

grant select on table "public"."Temporadas" to "service_role";

grant trigger on table "public"."Temporadas" to "service_role";

grant truncate on table "public"."Temporadas" to "service_role";

grant update on table "public"."Temporadas" to "service_role";

grant delete on table "public"."Torneos" to "anon";

grant insert on table "public"."Torneos" to "anon";

grant references on table "public"."Torneos" to "anon";

grant select on table "public"."Torneos" to "anon";

grant trigger on table "public"."Torneos" to "anon";

grant truncate on table "public"."Torneos" to "anon";

grant update on table "public"."Torneos" to "anon";

grant delete on table "public"."Torneos" to "authenticated";

grant insert on table "public"."Torneos" to "authenticated";

grant references on table "public"."Torneos" to "authenticated";

grant select on table "public"."Torneos" to "authenticated";

grant trigger on table "public"."Torneos" to "authenticated";

grant truncate on table "public"."Torneos" to "authenticated";

grant update on table "public"."Torneos" to "authenticated";

grant delete on table "public"."Torneos" to "postgres";

grant insert on table "public"."Torneos" to "postgres";

grant references on table "public"."Torneos" to "postgres";

grant select on table "public"."Torneos" to "postgres";

grant trigger on table "public"."Torneos" to "postgres";

grant truncate on table "public"."Torneos" to "postgres";

grant update on table "public"."Torneos" to "postgres";

grant delete on table "public"."Torneos" to "service_role";

grant insert on table "public"."Torneos" to "service_role";

grant references on table "public"."Torneos" to "service_role";

grant select on table "public"."Torneos" to "service_role";

grant trigger on table "public"."Torneos" to "service_role";

grant truncate on table "public"."Torneos" to "service_role";

grant update on table "public"."Torneos" to "service_role";


  create policy "Only self can query their data"
  on "public"."Socios"
  as permissive
  for select
  to public
using ((user_id = auth.uid()));



  create policy "Anyone can read"
  on "public"."Temporadas"
  as permissive
  for select
  to public
using (true);



  create policy "Only admin can write"
  on "public"."Temporadas"
  as permissive
  for all
  to public
using ((auth.role() = 'admin'::text));



  create policy "Everyone can read"
  on "public"."Torneos"
  as permissive
  for select
  to public
using (true);



  create policy "Only admin can write"
  on "public"."Torneos"
  as permissive
  for all
  to public
using ((auth.role() = 'admin'::text));



